name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  check:
    name: Nix check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - run: nix-shell -p nixpkgs-fmt --run 'nixpkgs-fmt --check .'
      - run: nix flake check

  cache:
    name: Cache derivations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - uses: cachix/cachix-action@v14
        with:
          name: cofob
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build derivations
        run: |
          nix build .#tmm
          nix build .#bps
          nix build .#tg-captcha
          nix build .#cofob-dev
