name: CI

on:
  push:

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  check:
    name: Nix check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - run: nix-shell -p nixpkgs-fmt --run 'nixpkgs-fmt --check .'
      - run: nix flake check .
